remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Chiara Alicia Wooldridge]
description: [This is a personal project that allows me to explore web development by creating my first website. It also helps me become more familiar with GitHub and Git.]
